#!/bin/sh

set -e

currentver=`dpkg-query --showformat='${Version}' --show libpango-*`
requiredver=1.44

# https://unix.stackexchange.com/a/285928
if [ "$(printf '%s\n' "$requiredver" "$currentver" | sort -V | head -n1)" = "$requiredver" ]; then
	sed -i 's/<border name="title_border" left="2" right="2" top="4" bottom="3"/<border name="title_border" left="2" right="2" top="4" bottom="4"/g' /usr/share/themes/human-theme/metacity-1/metacity-theme-1.xml
	sed -i 's/padding: 4px 3px; \/\* WARNING/padding: 4px 3px 2px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/inputs.css
	sed -i 's/padding: 3px; \/\* WARNING/padding: 3px 3px 2px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/inputs.css
	sed -i 's/margin: -7px -10px -4px; \/\* WARNING/margin: -7px -10px -5px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/containers.css
	echo "Update theme for Pango >= 1.44"
else
	sed -i 's/<border name="title_border" left="2" right="2" top="4" bottom="4"/<border name="title_border" left="2" right="2" top="4" bottom="3"/g' /usr/share/themes/human-theme/metacity-1/metacity-theme-1.xml
	sed -i 's/padding: 4px 3px 2px; \/\* WARNING/padding: 4px 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/inputs.css
	sed -i 's/padding: 3px 3px 2px; \/\* WARNING/padding: 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/inputs.css
	sed -i 's/margin: -7px -10px -5px; \/\* WARNING/margin: -7px -10px -4px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/containers.css
	echo "Update theme for Pango < 1.44"
fi
