[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Human Blue
Name[fr]=Human Bleu
Comment=The old Ubuntu Human theme for GTK 2.24 / 3.24 / 4.0. Blue variation.
Comment[fr]=L'ancien thème Ubuntu Human pour GTK 2.24 / 3.24 / 4.0. Variante bleue.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=old-ubuntu-human-blue
MetacityTheme=old-ubuntu-human-blue
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close