[Desktop Entry]
Type=X-GNOME-Metatheme
Name=old-ubuntu-human-blue
Comment=The old Ubuntu Human theme for... GTK 3.24. Blue variation.
Comment[fr]=Le vieux thème Ubuntu Human pour... GTK 3.24. Variante bleue.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=old-ubuntu-human-blue
MetacityTheme=old-ubuntu-human-blue
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close