[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Human Orange
Name[fr]=Human Orange
Comment=The old Ubuntu Human theme for GTK 2.24 / 3.24 / 4.0. Orange variation.
Comment[fr]=L'ancien thème Ubuntu Human pour GTK 2.24 / 3.24 / 4.0. Variante orange.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=old-ubuntu-human-orange
MetacityTheme=old-ubuntu-human-orange
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close