[Desktop Entry]
Type=X-GNOME-Metatheme
Name=old-ubuntu-human-green
Comment=The old Ubuntu Human theme for... GTK 3.24. Green variation.
Comment[fr]=Le vieux thème Ubuntu Human pour... GTK 3.24. Variante verte.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=old-ubuntu-human-green
MetacityTheme=old-ubuntu-human-green
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close