[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Human Green
Name[fr]=Human Vert
Comment=The old Ubuntu Human theme for GTK 2.24 / 3.20 / 4.0. Green variation.
Comment[fr]=L'ancien thème Ubuntu Human pour GTK 2.24 / 3.20 / 4.0. Variante verte.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=old-ubuntu-human-green
MetacityTheme=old-ubuntu-human-green
IconTheme=gnome
CursorTheme=DMZ-White
CursorSize=16
ButtonLayout=:minimize,maximize,close